load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "subworkspace1",
    srcs = ["test.go"],
    importpath = "github.com/google/shipshape/shipshape/cli/testdata/workspace2/subworkspace1",
    visibility = ["//visibility:public"],
)
